package cn.com.incito.driver.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import cn.com.incito.driver.dao.AgentDao;
import cn.com.incito.driver.dao.CommentDao;
import cn.com.incito.driver.dao.OrdersAllDao;
import cn.com.incito.driver.dao.OrdersObligationDao;
import cn.com.incito.driver.dao.OrdersDistributionDao;
import cn.com.incito.driver.dao.OrdersSignDao;
import cn.com.incito.driver.dao.OrdersEvaluatedDao;
import cn.com.incito.driver.dao.OrdersCanceledDao;
import cn.com.incito.driver.dao.OrdersReimburseDao;
import cn.com.incito.driver.dao.OrdersReceivedDao;
import cn.com.incito.driver.dao.GoodsAvailableDao;
import cn.com.incito.driver.dao.GoodsHasAvailableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 5): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 5;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        AgentDao.createTable(db, ifNotExists);
        CommentDao.createTable(db, ifNotExists);
        OrdersAllDao.createTable(db, ifNotExists);
        OrdersObligationDao.createTable(db, ifNotExists);
        OrdersDistributionDao.createTable(db, ifNotExists);
        OrdersSignDao.createTable(db, ifNotExists);
        OrdersEvaluatedDao.createTable(db, ifNotExists);
        OrdersCanceledDao.createTable(db, ifNotExists);
        OrdersReimburseDao.createTable(db, ifNotExists);
        OrdersReceivedDao.createTable(db, ifNotExists);
        GoodsAvailableDao.createTable(db, ifNotExists);
        GoodsHasAvailableDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        AgentDao.dropTable(db, ifExists);
        CommentDao.dropTable(db, ifExists);
        OrdersAllDao.dropTable(db, ifExists);
        OrdersObligationDao.dropTable(db, ifExists);
        OrdersDistributionDao.dropTable(db, ifExists);
        OrdersSignDao.dropTable(db, ifExists);
        OrdersEvaluatedDao.dropTable(db, ifExists);
        OrdersCanceledDao.dropTable(db, ifExists);
        OrdersReimburseDao.dropTable(db, ifExists);
        OrdersReceivedDao.dropTable(db, ifExists);
        GoodsAvailableDao.dropTable(db, ifExists);
        GoodsHasAvailableDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(AgentDao.class);
        registerDaoClass(CommentDao.class);
        registerDaoClass(OrdersAllDao.class);
        registerDaoClass(OrdersObligationDao.class);
        registerDaoClass(OrdersDistributionDao.class);
        registerDaoClass(OrdersSignDao.class);
        registerDaoClass(OrdersEvaluatedDao.class);
        registerDaoClass(OrdersCanceledDao.class);
        registerDaoClass(OrdersReimburseDao.class);
        registerDaoClass(OrdersReceivedDao.class);
        registerDaoClass(GoodsAvailableDao.class);
        registerDaoClass(GoodsHasAvailableDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
