package cn.com.incito.driver.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GOODS_HAS_AVAILABLE.
 */
public class GoodsHasAvailable {

    private Long id;
    private String mId;
    private String originalprovince;
    private String originalcity;
    private String originalregion;
    private String receiptprovince;
    private String receiptcity;
    private String receiptregion;
    private String goodsname;
    private String goodstype;
    private String infofare;
    private String fare;
    private String weight;
    private String volume;
    private String count;
    private String carlength;
    private String generatetime;
    private String goodstime;
    private String completetime;
    private String goodsid;
    private String carid;
    private String grabflag;
    private String grabresult;
    private String orderid;
    private String failurereason;
    private Long createtime;

    public GoodsHasAvailable() {
    }

    public GoodsHasAvailable(Long id) {
        this.id = id;
    }

    public GoodsHasAvailable(Long id, String mId, String originalprovince, String originalcity, String originalregion, String receiptprovince, String receiptcity, String receiptregion, String goodsname, String goodstype, String infofare, String fare, String weight, String volume, String count, String carlength, String generatetime, String goodstime, String completetime, String goodsid, String carid, String grabflag, String grabresult, String orderid, String failurereason, Long createtime) {
        this.id = id;
        this.mId = mId;
        this.originalprovince = originalprovince;
        this.originalcity = originalcity;
        this.originalregion = originalregion;
        this.receiptprovince = receiptprovince;
        this.receiptcity = receiptcity;
        this.receiptregion = receiptregion;
        this.goodsname = goodsname;
        this.goodstype = goodstype;
        this.infofare = infofare;
        this.fare = fare;
        this.weight = weight;
        this.volume = volume;
        this.count = count;
        this.carlength = carlength;
        this.generatetime = generatetime;
        this.goodstime = goodstime;
        this.completetime = completetime;
        this.goodsid = goodsid;
        this.carid = carid;
        this.grabflag = grabflag;
        this.grabresult = grabresult;
        this.orderid = orderid;
        this.failurereason = failurereason;
        this.createtime = createtime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMId() {
        return mId;
    }

    public void setMId(String mId) {
        this.mId = mId;
    }

    public String getOriginalprovince() {
        return originalprovince;
    }

    public void setOriginalprovince(String originalprovince) {
        this.originalprovince = originalprovince;
    }

    public String getOriginalcity() {
        return originalcity;
    }

    public void setOriginalcity(String originalcity) {
        this.originalcity = originalcity;
    }

    public String getOriginalregion() {
        return originalregion;
    }

    public void setOriginalregion(String originalregion) {
        this.originalregion = originalregion;
    }

    public String getReceiptprovince() {
        return receiptprovince;
    }

    public void setReceiptprovince(String receiptprovince) {
        this.receiptprovince = receiptprovince;
    }

    public String getReceiptcity() {
        return receiptcity;
    }

    public void setReceiptcity(String receiptcity) {
        this.receiptcity = receiptcity;
    }

    public String getReceiptregion() {
        return receiptregion;
    }

    public void setReceiptregion(String receiptregion) {
        this.receiptregion = receiptregion;
    }

    public String getGoodsname() {
        return goodsname;
    }

    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname;
    }

    public String getGoodstype() {
        return goodstype;
    }

    public void setGoodstype(String goodstype) {
        this.goodstype = goodstype;
    }

    public String getInfofare() {
        return infofare;
    }

    public void setInfofare(String infofare) {
        this.infofare = infofare;
    }

    public String getFare() {
        return fare;
    }

    public void setFare(String fare) {
        this.fare = fare;
    }

    public String getWeight() {
        return weight;
    }

    public void setWeight(String weight) {
        this.weight = weight;
    }

    public String getVolume() {
        return volume;
    }

    public void setVolume(String volume) {
        this.volume = volume;
    }

    public String getCount() {
        return count;
    }

    public void setCount(String count) {
        this.count = count;
    }

    public String getCarlength() {
        return carlength;
    }

    public void setCarlength(String carlength) {
        this.carlength = carlength;
    }

    public String getGeneratetime() {
        return generatetime;
    }

    public void setGeneratetime(String generatetime) {
        this.generatetime = generatetime;
    }

    public String getGoodstime() {
        return goodstime;
    }

    public void setGoodstime(String goodstime) {
        this.goodstime = goodstime;
    }

    public String getCompletetime() {
        return completetime;
    }

    public void setCompletetime(String completetime) {
        this.completetime = completetime;
    }

    public String getGoodsid() {
        return goodsid;
    }

    public void setGoodsid(String goodsid) {
        this.goodsid = goodsid;
    }

    public String getCarid() {
        return carid;
    }

    public void setCarid(String carid) {
        this.carid = carid;
    }

    public String getGrabflag() {
        return grabflag;
    }

    public void setGrabflag(String grabflag) {
        this.grabflag = grabflag;
    }

    public String getGrabresult() {
        return grabresult;
    }

    public void setGrabresult(String grabresult) {
        this.grabresult = grabresult;
    }

    public String getOrderid() {
        return orderid;
    }

    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    public String getFailurereason() {
        return failurereason;
    }

    public void setFailurereason(String failurereason) {
        this.failurereason = failurereason;
    }

    public Long getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

}
